Feature/componente3
CamiloGilFranco/TableTop-FE pull request #11
Opened 2023-02-25 15:04 UTC by dgaleano201611

me hacen feedback de este componente.

2023-02-25 15:36 UTC, Nicolas-Rodriguez-Ch requested changes
Esta bien, asegurate de resolver confilctos antes de hacer el merge

2023-02-27 15:58 UTC, Diegodag35 commented
Conflictos arreglados

2023-02-27 16:10 UTC, CamiloGilFranco approved these changes

2023-02-27 17:17 UTC, Nicolas-Rodriguez-Ch reviewed
Muy bien!

2023-02-27 17:17 UTC, merged