Feature/language refactor
CamiloGilFranco/TableTop-FE pull request #56
Opened 2023-04-04 03:32 UTC by Nicolas-Rodriguez-Ch

refactors the language feature in the components

2023-04-04 17:26 UTC, ht1204 commented on src/components/GeneralAdminModal/GeneralAdminModal.jsx
> +  const language = useSelector(state => state.languageReducer )
Fix this small space:
```javascript
const language = useSelector(state => state.languageReducer)
```
This is not a blocker, but details are important

2023-04-04 17:27 UTC, ht1204 commented on src/components/GeneralAdminModal/GeneralAdminModal.jsx
>      if (title.length <= 1 || typeof title !== 'string') {
Here, why not?
```javascript
const isTitle = !title.length || typeof title !== 'string'
if(isTitle) {...
```

2023-04-04 17:28 UTC, ht1204 commented on src/components/GeneralAdminModal/GeneralAdminModal.jsx
>      if (newCategories.length === 0) {
Replace:
```javascript
if (!newCategories.length) {
```

2023-04-04 17:28 UTC, ht1204 commented on src/components/GeneralAdminModal/GeneralAdminModal.jsx
>      if (Object.keys(validationErrors).length > 0) {
Why not?
```javascript
if(Object.keys(validationErrors).length){
...
```

2023-04-04 17:30 UTC, ht1204 commented on src/components/OrderSuccesful/OrderSuccesful.jsx
>    console.log(orderID);
is this ```console.log``` still necessary? If that is not case, please, remove.

2023-04-04 17:33 UTC, ht1204 commented on src/components/Overview/Overview.jsx
>            {schedule.map((element, index) => (
Suggest for JS conditional rendering for maps:
```js
{schedule && schedule.map(....
```

2023-04-04 17:33 UTC, ht1204 commented on src/components/Overview/Overview.jsx
>            {address.map((element, index) => (
Same here and each case like this.

2023-04-04 17:37 UTC, ht1204 commented on src/components/Overview/Overview.jsx
>              <li key={index}>{element}</li>
Consider another way for mapping instead of index [why not using index](https://legacy.reactjs.org/docs/lists-and-keys.html#:~:text=We%20don't%20recommend%20using,cause%20issues%20with%20component%20state.) Please, consider replace the index by the entity id or using uuid or nanoid, this would be considered everytime for mapping components.

2023-04-04 17:44 UTC, ht1204 commented on src/components/ReviewsComponent/SingleReviewComponent.jsx
>    const stars = (rating) => {
This star generator, is not bad, but if there is time for experimenting, consider a proposal enhancement to adapt:
[star generator](https://github.com/codegeous/react-component-depot/blob/master/src/components/Rate/index.js)

2023-04-04 17:45 UTC, ht1204 commented on src/components/payment/Payment.jsx
> +                  {languageSelector(language, 'paymentMakePayment')}
a small indentation here.

2023-04-04 17:46 UTC, ht1204 commented on src/pages/GeneralAdminView/GeneralAdminView.jsx
> +              {languageSelector(language, 'generalAdminList')} #{restaurants.length} restaurant{restaurants.length > 1 ? 's' : ''} {language === 'en' ? 'and': 'y'} #{users.length} {language === 'en'?
```js
restaurant{restaurants.length ? 's' : ''}
```

2023-04-04 17:47 UTC, ht1204 commented on src/pages/GeneralAdminView/GeneralAdminView.jsx
>                  {categoriesArr.map((checkbox)=> (
```js
{categoriesArr && categoriesArr.map((checkbox)=> ( ...
```

2023-04-04 17:48 UTC, ht1204 requested changes
Please, consider the comments that I left, attentive to any updates and/or progress.

2023-04-04 21:50 UTC, Nicolas-Rodriguez-Ch commented
Already done with the suggested changes

2023-04-05 01:31 UTC, ht1204 commented on src/pages/GeneralAdminView/GeneralAdminView.jsx
> +              {languageSelector(language, 'generalAdminList')} #{restaurants.length} restaurant{restaurants.length > 1 ? 's' : ''} {language === 'en' ? 'and': 'y'} #{users.length} {language === 'en'?
Resolved

2023-04-05 01:32 UTC, ht1204 commented on src/components/payment/Payment.jsx
> +                  {languageSelector(language, 'paymentMakePayment')}
Resolved

2023-04-05 01:32 UTC, ht1204 commented on src/components/ReviewsComponent/SingleReviewComponent.jsx
>    const stars = (rating) => {
Please, consider this enhancement in a future PR, if it's possible.

2023-04-05 01:35 UTC, ht1204 commented on src/components/Overview/Overview.jsx
>              <li key={index}>{element}</li>
Please, consider another alternatives for mapping components instead of index, check the link and you could use the item id, for example: ```<li key={element.id}>{element}</li>``` check and replace in each case for rendering.

2023-04-05 01:36 UTC, ht1204 commented on src/components/OrderSuccesful/OrderSuccesful.jsx
>    console.log(orderID);
Done, resolved.

2023-04-05 01:36 UTC, ht1204 commented on src/components/GeneralAdminModal/GeneralAdminModal.jsx
>      if (Object.keys(validationErrors).length > 0) {
Done.

2023-04-05 01:37 UTC, ht1204 commented on src/components/GeneralAdminModal/GeneralAdminModal.jsx
>      if (newCategories.length === 0) {
Done.

2023-04-05 01:37 UTC, ht1204 commented on src/components/GeneralAdminModal/GeneralAdminModal.jsx
>      if (title.length <= 1 || typeof title !== 'string') {
Done.

2023-04-05 01:38 UTC, ht1204 commented on src/components/GeneralAdminModal/GeneralAdminModal.jsx
> +  const language = useSelector(state => state.languageReducer )
Done.

2023-04-05 01:38 UTC, ht1204 approved these changes
Keep doing a good job and moving forward, enhancements can be done eventually.

2023-04-05 01:38 UTC, merged